name: biftech
description: Biftech App Assignment - Multi-language Flowchart Voting App
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  bloc: ^9.0.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_localizations:
    sdk: flutter
  formz: ^0.6.1
  go_router: ^13.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.19.0
  neopop: ^1.0.2
  path_provider: ^2.1.2

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  mocktail: ^1.0.4
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
  generate: true
